services:
  aura_intelligence-gateway:
    image: ${AURA_IMAGE:-aura_intelligence:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      AURA_GATEWAY_TOKEN: ${AURA_GATEWAY_TOKEN}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${AURA_CONFIG_DIR}:/home/node/.aura
      - ${AURA_WORKSPACE_DIR}:/home/node/aura
    ports:
      - "${AURA_GATEWAY_PORT:-18789}:18789"
      - "${AURA_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${AURA_GATEWAY_BIND:-lan}",
        "--port",
        "${AURA_GATEWAY_PORT:-18789}"
      ]

  aura_intelligence-cli:
    image: ${AURA_IMAGE:-aura_intelligence:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      BROWSER: echo
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${AURA_CONFIG_DIR}:/home/node/.aura
      - ${AURA_WORKSPACE_DIR}:/home/node/aura
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]
